name: Get Secrets
env: 
  APP_NAME: PC
    
on:    
  push:
    branches: [main]
    paths : '.github/workflows/GetSecrets.yml'
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Get JSON Secret
        id: getJsonSecret
        shell: bash
        run: |
           echo test= '${{secrets.TEST_AZ_CREDS}}' jq '.[] | .clientId, .clientSecret, .subscriptionId, .tenantId' 
           echo $test
        env:
           GITHUB_TOKEN : ${{ secrets.TEST_AZ_CREDS }}
           
      - name: Azure Login with Env var
        uses: Azure/login@v1
        with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
         creds: ${{env.GITHUB_TOKEN}} 
